name: Build and Push to GitHub Pages Branch

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: Tutorials/whatiswot/website/package-lock.json
      - name: Change to folder
        run: cd Tutorials/whatiswot/website
      - name: Install dependencies
        run: npm ci
      - name: Create final folder
        run: mkdir -p deploy/tutorials/whatiswot
      - name: Build website
        run: npm run build
      - name: Move build to final folder
        run: mv build deploy/tutorials/whatiswot
      - name: Deploy to GitHub Pages
        run: |
             git config user.name 'Ege Korkan'
             git config user.email 'egekorkan@gmail.com'
             git add -f deploy
             git commit -a -s -m "push the build to github pages branch"
             git push origin docusaurus-whatiswot
